## Create a gpg key for this installation.
# It's default installed by Debian, so no need to install/get it.
# http://www.gnupg.org/documentation/manuals/gnupg-devel/Unattended-GPG-key-generation.html
---
- name: Copy the gpg configuration key creation file
  template: src=gpg_keygen.conf dest=/root/gpg_keygen.conf mode=600
  tags: gnupg

- name: Create gpg keypair.
  command: gpg --batch --gen-key /root/gpg_keygen.conf
    creates=/root/.gnupg/pubring.gpg
  tags: gnupg

- name: Copy the GPG configuration
  copy: src=gpg.conf dest=/root/.gnupg/gpg.conf
  tags: gnupg

- name: Export the public key.
  command: gpg --armour --output /root/gpg_machine_key.pub --export {{ansible_hostname}}
    creates=/root/gpg_machine_key.pub
  tags: gnupg

- name: Publish the public key.
  command: cp /root/gpg_machine_key.pub /var/www/gpg_machine_key.pub
    creates=/var/www/gpg_machine_key.pub
  tags: gnupg

