---
- include: ntp.yml
- include: fail2ban.yml
- include: cron_apt.yml

# HARDEN

##- include: file_integrity.yml
##- include: firewall.yml
##- include: callhome.yml

# Privacy
##- include: logrotate.yml
