## changes common to all systems.
---
- include: ntp.yml
- include: cron_apt.yml

- name: Install extra packages needed for anisable
  apt: pkg={{item}} state=present
  with_items:
    - python-pycurl
