## changes common to all systems.
---
- name: Directory to store local facts
  file: path=/etc/ansible/facts.d state=directory

- name: Directory to store public information
  file: path=/var/www state=directory

- include: haveged.yml # Start collecting entropy as soon as we can.
- include: ntp.yml
- include: cron_apt.yml
- include: gpg_key.yml
- include: ssh_identity.yml
