---
# file: roles/common/tasks/main.yml

- name: be sure ntp is installed
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - ntp
    - ntpdate
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp


# HARDEN
# IP Tables
# fail2ban