---
- include: ntp.yml
- include: fail2ban.yml
- include: cron_apt.yml

# HARDEN
##- include: beter_entropy.yml
##- include: harden_sshd.yml
##- include: portsentry.yml
##- include: file_integrity.yml
##- include: harden_networking.yml

# Privacy
##- include: logrotate.yml

# Common services
##- include: webserver.yml