## Get and set good time values by using internet timeservices via the NTP protocol.
---
- name: be sure ntp is installed
  apt: pkg=ntp state=present update_cache=yes
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp
