## Install duplicity backup client 
---
# install duplicity
- name: ensure duplicity packages are installed.
  apt: pkg=duplicity state=present

- name: create place for duplicity-configration
  file: dest=/etc/duplicity/filelist.d state=directory

- name: Install duplicity backup script
  copy: src=../contrib/duplicity-backup/duplicity-backup.sh dest=/usr/local/sbin/duplicity-backup.sh mode=0755

- name: copy duplicity configuration file.
  template: src=duplicity-backup.conf dest=/etc/duplicity/duplicity-backup.conf

- name: Add the standard directories to backup
  copy: src=filelist_10_main.txt dest=/etc/duplicity/filelist.d/10_main.txt
# This should work, but doesn't.
#  notify: 
#    - restart duplicity

- name: Create the list of files to backup. 
  assemble: src=/etc/duplicity/filelist.d/ dest=/etc/duplicity/filelist.txt

- name: setup the backup frequency
  cron: name="backup with duplicity" special_time=daily
    job="duplicity-backup.sh -c /etc/duplicity/duplicity-backup.conf -b"

