## Install the lightweight nginx webserver.
---
- include: ssl_certificates.yml

- name: be sure nginx is installed
  apt: pkg=nginx state=present update_cache=yes

- name: remove server version identifcation from http responses.
  lineinfile: dest=/etc/nginx/nginx.conf
              regexp="^\s*# server_tokens" backrefs=yes line="server_tokens off;"
  notify:
    - restart nginx

- name: Copy nginx default website configuration file.
  template: src=nginx_default.j2 dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: be sure nginx sites are enabled.
  file: state=link src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default
  notify:
    - restart nginx

- name: add the siteroot configuration directory
  file: dest=/etc/nginx/sites-available/default.d/ state=directory

- name: add the siteroot configuration to nginx.
  copy: src=00_siteroot.conf dest=/etc/nginx/sites-available/default.d/00_siteroot.conf
        backup=yes
  notify:
    - restart nginx

- name: be sure nginx is running and enabled
  service: name=nginx state=running enabled=yes
