---
- hosts: closetboxen
  roles:
    - { role: common, sudo: yes }
    - { role: harden, sudo: yes }
    #- { role: privacy, sudo: yes }
    - { role: webserver, sudo: yes }
    #- { role: filehost, sudo: yes }
    #- { role: emailhost, sudo: yes }
    #- { role: chatserver, sudo: yes }
    #- { role: socialmedia, sudo: yes }
    #- { role: publishing, sudo: yes }