---
- hosts: closetboxen
  roles:
    - { role: common, sudo: yes, tags:[common] }
    - { role: harden, sudo: yes }
    #- { role: privacy, sudo: yes }
    - { role: nginx, sudo: yes, tags:[nginx] }
    - { role: owncloud, sudo: yes, tags:[owncloud] }
    #- { role: emailhost, sudo: yes }
    #- { role: chatserver, sudo: yes }
    #- { role: socialmedia, sudo: yes }
    #- { role: publishing, sudo: yes }