---
- name: Install the Closetbox software
  hosts: all
  roles:
    - { role: common, sudo: yes, tags:[common] }
    - { role: harden, sudo: yes }
    #- { role: privacy, sudo: yes }
    - { role: duplicity, sudo: yes, tags:[backup, duplicity] } # Create the backup client.
    - { role: nginx, sudo: yes, tags:[nginx] }
    #- { role: tor-hidden-services, sudo: yes, tags:[anonymity] }
    - { role: owncloud, sudo: yes, tags:[owncloud] }
    #- { role: emailhost, sudo: yes }
    #- { role: chatserver, sudo: yes }
    #- { role: socialmedia, sudo: yes }
    #- { role: publishing, sudo: yes }
    #- { role: development, sudo: yes } ## This is to add some convenience when working on the closetbox configuration.